### ISSUE TITLE
Request for Contact

### ISSUE THREAD

**Issue by priyankeshh** [abhijeetsingh0401/vizuaraKids#1]
Hello Abhijeet,

I wanted to discuss some topics related to GSoC with you. If possible, could you share a way for us to connect, like your LinkedIn? That would be really helpful.

**Comment by abhijeetsingh0401** [comment]
Hi @priyankeshh could you please me mail me at vayuabhijeet@gmail.com I would be happy to help you in anyway 
thanks !
